### ISSUE TITLE
Include 3D simulation in test suite + tutorials

### ISSUE THREAD

**Issue by martijnende** [ydluo/qdyn#52]
Since 3D simulations are a prominent feature of QDYN, they should be tested on a regular basis. For new users, it would be helpful to have a tutorial as a starting point for more advanced simulations.

## To-do:

- [x] Create Jupyter notebook with a simple 3D simulation (including dynamic OX output?)
- [x] Add notebook to documentation (advanced tutorial)
- [ ] Generate frozen results for benchmark testing
- [ ] Update test suite
