### ISSUE TITLE
Read mesh coordinates from the input file by default

### ISSUE THREAD

**Issue by martijnende** [ydluo/qdyn#69]
Currently QDYN internally generates a mesh, except for 3D MPI simulations. Since the Python wrapper already pre-computes a mesh with default settings, we might as well shift the burden from FORTRAN to Python/Matlab, and always read the mesh from the input file.

# To-do

- [ ] Verify that the default mesh generator in Python outputs the same results as the one in FORTRAN
- [ ] Create Python routines for standard fault configurations
- [ ] Create an internal check that the along-strike direction is co-linear for each row of the mesh, and that the number of elements in that direction is an integer power of 2 (both are required by the FFT)
- [ ] Design an integration test for an unambiguous fault geometry (i.e. mesh in == mesh out)
